//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.26 at 11:09:27 AM CLST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://mdwcorp.falabella.com/LOG/CORP/schema/WMOS/Appointment/Req", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package corp.corp.appointment.appointmentserviceV10.domain.model;
